name: flutter_credit_card_scanner
description: "A Flutter package that utilizes the device camera to scan and extract credit card information."
version: 0.7.4
homepage: https://github.com/nimr77/Flutter_credit_card_scanner

environment:
      sdk: ^3.5.1
      flutter: '>=3.3.0'

dependencies:
      camera: ^0.11.0+2
      flutter:
        sdk: flutter
      google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
      flutter_test:
        sdk: flutter

flutter:
      plugin:
        platforms:
          android:
            package: com.example.flutter_credit_card_scanner
            pluginClass: CreditCardScannerPlugin
          ios:
            pluginClass: CreditCardScannerPlugin